# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MVVMRXSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'RxSwift', '~> 5'
	pod 'RxCocoa', '~> 5'
    pod 'SwiftLint'
    pod 'KRProgressHUD'
  # Pods for MVVMRXSwift

end

target 'MVVMRXSwiftTests' do
    use_frameworks!
    pod 'RxSwift', '~> 5'
end
